import type { Course, CourseNode, LessonSection, PracticeItem } from './types'

const page = (number: string) => `raw/udl/textbook/pages/ch12-transformers/page_${number}.md`
const practiceId = (nodeId: string) => `practice.${nodeId}`

function lesson(
  question: string,
  answer: string,
  math: string,
  practiceMove: string,
  misconception: string,
): LessonSection[] {
  return [
    {
      title: 'Ask Before Naming',
      body: `**Question.** ${question}\n\n**Answer.** ${answer}\n\nThis is the Little-style move: make one prediction, check it, then let the name arrive after the idea has already done a job.`,
    },
    {
      title: 'Compress The Operation',
      body: math,
    },
    {
      title: 'Do And Repair',
      body: `**Do.** ${practiceMove}\n\n**Common trap.** ${misconception}`,
    },
  ]
}

function node(input: Omit<CourseNode, 'practiceIds'>): CourseNode {
  return {
    ...input,
    practiceIds: [practiceId(input.id)],
  }
}

const nodes: CourseNode[] = [
  node({
    id: 'problem.variable-length-text',
    title: 'Why Text Breaks Fully Connected Nets',
    track: 'nlp',
    stage: 'problem-framing',
    summary:
      'Text examples have different lengths, so a fixed fully connected input layer is the wrong starting point.',
    sourceAnchors: [page('0207'), page('0208')],
    prerequisites: [],
    equation: '37 \\times 1024 = 37888',
    graph: { x: 7, y: 16 },
    lesson: lesson(
      'If one sentence has 7 tokens and another has 700, can the same dense input layer ingest both without padding or truncation?',
      'Not naturally. A dense layer expects a fixed number of inputs, while text arrives as variable-length sequences.',
      'A sentence with $N$ tokens and embedding width $D$ has $ND$ scalar inputs. As $N$ changes, the raw input size changes too.',
      'Compute the scalar count for $N=37,D=1024$, then for $N=512,D=1024$. Say what changed and what stayed reusable.',
      'The mistake is thinking "more words" only means more data. It also changes the shape that a naive dense layer would expect.',
    ),
    littlePath: [
      'Count the scalar inputs for one short passage.',
      'Change only the number of tokens and count again.',
      'Ask what kind of network can reuse work across positions.',
    ],
    masteryEvidence: ['Compute sequence input size as $ND$.', 'Explain why variable length pressures the architecture.'],
    commonMisconceptions: ['Padding alone solves learning long-range dependencies.'],
  }),
  node({
    id: 'problem.parameter-sharing',
    title: 'Parameter Sharing Across Positions',
    track: 'architecture',
    stage: 'problem-framing',
    summary:
      'A transformer reuses the same learned maps at every token position, like convolution reuses filters over image locations.',
    sourceAnchors: [page('0207'), page('0208')],
    prerequisites: ['problem.variable-length-text'],
    equation: '\\mathbf{v}_n = \\boldsymbol{\\beta}_v + \\Omega_v\\mathbf{x}_n',
    graph: { x: 7, y: 34 },
    lesson: lesson(
      'Should the model relearn the meaning of "dog" separately at position 3, position 40, and position 400?',
      'No. The local operation should be shared; the context can differ, but the token-processing rule should be reusable.',
      'The same parameters $\\Omega_v,\\boldsymbol{\\beta}_v$ are applied to each token vector $\\mathbf{x}_n$. The subscript changes; the weights do not.',
      'Mark which parts change in $\\mathbf{v}_1,\\mathbf{v}_2,\\mathbf{v}_3$ and which parameters are shared.',
      'A common trap is to confuse shared parameters with identical outputs. Same rule, different token vector, different result.',
    ),
    littlePath: [
      'Write the value computation for token 1.',
      'Write it for token 2 and circle the reused parameters.',
      'Name parameter sharing only after the pattern is visible.',
    ],
    masteryEvidence: ['Identify shared versus position-specific quantities.', 'Explain why sharing reduces parameter growth.'],
    commonMisconceptions: ['Shared parameters force all positions to have the same representation.'],
  }),
  node({
    id: 'problem.context-routing',
    title: 'Context As Routing',
    track: 'attention',
    stage: 'problem-framing',
    summary:
      'Ambiguous words need information routed from other words; the route depends on the current input, not a fixed wire.',
    sourceAnchors: [page('0208'), page('0209')],
    prerequisites: ['problem.parameter-sharing'],
    equation: '\\mathbf{sa}_n[\\mathbf{x}_{\\bullet}] = \\sum_{m=1}^{N} a[\\mathbf{x}_m,\\mathbf{x}_n]\\mathbf{v}_m',
    graph: { x: 7, y: 52 },
    lesson: lesson(
      'In "the restaurant served the sandwich before it closed", what should "it" borrow information from?',
      'It should borrow from "restaurant" more than from "sandwich" for the closing event. Attention is the learned routing pattern.',
      'The output at position $n$ is a weighted sum of values from positions $m$. The weights $a[\\mathbf{x}_m,\\mathbf{x}_n]$ decide the route.',
      'Draw three arrows into one token, assign weights that sum to 1, and state the story those weights tell.',
      'Do not treat attention as a hard lookup. Most rows are mixtures, even when one source dominates.',
    ),
    littlePath: [
      'Pick one ambiguous token.',
      'Choose candidate source tokens.',
      'Convert the explanation into a row of weights.',
    ],
    masteryEvidence: ['Read an attention row as routing.', 'Connect ambiguity resolution to data-dependent weights.'],
    commonMisconceptions: ['Attention must select exactly one previous word.'],
  }),
  node({
    id: 'math.vector-embedding-shape',
    title: 'Token Vectors And Shape',
    track: 'math',
    stage: 'problem-framing',
    summary:
      'Each token representation is a length-D vector; the whole sequence is a D by N matrix in the UDL convention.',
    sourceAnchors: [page('0208'), page('0212')],
    prerequisites: ['problem.variable-length-text'],
    equation: '\\mathbf{x}_n \\in \\mathbb{R}^{D\\times 1},\\quad \\mathbf{X}\\in\\mathbb{R}^{D\\times N}',
    graph: { x: 7, y: 70 },
    lesson: lesson(
      'If there are 5 tokens and each has 4 features, is the sequence one vector or a grid of token vectors?',
      'It is a matrix: one column per token, one row per feature dimension.',
      'UDL stores token vectors as columns: $\\mathbf{X}\\in\\mathbb{R}^{D\\times N}$. Many libraries use batch-first or sequence-first layouts, so always name axes.',
      'For $D=4,N=5$, write the shape of $X$, $X^T$, and one token vector $x_3$.',
      'The trap is memorizing a convention without tracking what each axis means.',
    ),
    littlePath: ['Start with one token vector.', 'Stack five token vectors.', 'Name the axes before doing matrix math.'],
    masteryEvidence: ['Infer $D\\times N$ sequence shape.', 'Translate between column-token and row-token conventions.'],
    commonMisconceptions: ['The number of tokens and the embedding dimension can be swapped without consequence.'],
  }),
  node({
    id: 'math.matrix-linear-map',
    title: 'Linear Maps For Each Token',
    track: 'math',
    stage: 'problem-framing',
    summary:
      'A learned matrix turns one token representation into another while preserving the reusable per-token rule.',
    sourceAnchors: [page('0208'), page('0210')],
    prerequisites: ['math.vector-embedding-shape', 'problem.parameter-sharing'],
    equation: '\\mathbf{z}_n = \\boldsymbol{\\beta}+\\Omega\\mathbf{x}_n',
    graph: { x: 7, y: 88 },
    lesson: lesson(
      'What does a projection matrix do to one token vector?',
      'It remixes its features into a new feature list. In attention, different projections create values, queries, and keys.',
      'A map $\\Omega\\in\\mathbb{R}^{D_{out}\\times D_{in}}$ transforms $\\mathbf{x}_n\\in\\mathbb{R}^{D_{in}}$ into $\\Omega\\mathbf{x}_n\\in\\mathbb{R}^{D_{out}}$.',
      'Given $D_{in}=4,D_{out}=2$, write the shape of $\\Omega$ and the output vector.',
      'Do not read a projection as moving a token to a physical location. It changes coordinates in feature space.',
    ),
    littlePath: ['Multiply a tiny 2 by 3 matrix by a vector.', 'Attach the same map to two tokens.', 'Name it a projection.'],
    masteryEvidence: ['Compute simple output shapes.', 'Explain why the same map can be reused at every token.'],
    commonMisconceptions: ['Projection means selecting one original feature unchanged.'],
  }),
  node({
    id: 'math.dot-product',
    title: 'Dot Product As Match Score',
    track: 'math',
    stage: 'problem-framing',
    summary:
      'A query-key dot product multiplies aligned features and sums them into one match score.',
    sourceAnchors: [page('0210'), page('0211')],
    prerequisites: ['math.vector-embedding-shape'],
    equation: 's_{mn}=\\mathbf{k}_m^T\\mathbf{q}_n=\\sum_{d=1}^{D_q} k_{dm}q_{dn}',
    graph: { x: 20, y: 12 },
    lesson: lesson(
      'If two feature lists point in similar directions, should their match score be high or low?',
      'High. The dot product rewards features that are large in the same coordinates.',
      'For attention, the key from source token $m$ meets the query from target token $n$: $s_{mn}=\\mathbf{k}_m^T\\mathbf{q}_n$.',
      'Compute $[1,2,3]\\cdot[3,1,2]$ and identify which coordinate contributes most.',
      'A large dot product is not automatically "semantic truth"; it is a learned similarity under the model features.',
    ),
    littlePath: ['Multiply feature pairs.', 'Add the products.', 'Interpret the sum as alignment.'],
    masteryEvidence: ['Compute dot products.', 'Read dot product size as learned alignment.'],
    commonMisconceptions: ['Dot product measures word identity directly.'],
  }),
  node({
    id: 'math.weighted-average',
    title: 'Weighted Mixtures',
    track: 'math',
    stage: 'problem-framing',
    summary:
      'Attention outputs are mixtures of value vectors; attention weights are shares in that mixture.',
    sourceAnchors: [page('0208'), page('0209')],
    prerequisites: ['math.vector-embedding-shape'],
    equation: '\\mathbf{y}=\\sum_{m=1}^{N} a_m\\mathbf{v}_m,\\quad \\sum_m a_m=1',
    graph: { x: 20, y: 28 },
    lesson: lesson(
      'If value vectors are ingredients, what do the attention weights do?',
      'They decide how much of each ingredient enters the output representation.',
      'A weighted mixture preserves scale when the weights are nonnegative and sum to 1. Attention uses one such mixture for each output token.',
      'Mix scalar values 2, 4, and 10 using weights 0.5, 0.25, and 0.25. Then say which value most influenced the result.',
      'The trap is saying attention copies a value. It can copy approximately, but the operation is a weighted sum.',
    ),
    littlePath: ['Mix scalars.', 'Mix short vectors.', 'Read one attention row as mixture recipe.'],
    masteryEvidence: ['Compute weighted mixtures.', 'Explain why row weights sum to one.'],
    commonMisconceptions: ['The highest weight deletes all other values.'],
  }),
  node({
    id: 'prob.softmax-normalization',
    title: 'Softmax Turns Scores Into Shares',
    track: 'probability',
    stage: 'problem-framing',
    summary:
      'Softmax converts arbitrary scores into positive attention weights whose row or column sums to one.',
    sourceAnchors: [page('0210'), page('0211'), page('0239')],
    prerequisites: ['math.dot-product', 'math.weighted-average'],
    equation: 'a_{mn}=\\frac{\\exp(s_{mn})}{\\sum_{m^{\\prime}=1}^{N}\\exp(s_{m^{\\prime}n})}',
    graph: { x: 20, y: 44 },
    lesson: lesson(
      'Can raw scores like -3, 1, and 5 be mixture weights?',
      'No. A mixture needs nonnegative shares that sum to 1. Softmax creates those shares.',
      'Softmax exponentiates each score, then divides by the total exponentiated mass. Larger scores receive larger shares, but every finite score remains positive.',
      'Without calculating exact decimals, rank the softmax shares for scores -3, 1, and 5.',
      'Dividing raw scores by their raw sum is not softmax and can produce negative or unstable shares.',
    ),
    littlePath: ['Reject raw negative scores.', 'Make positive amounts.', 'Normalize into shares.'],
    masteryEvidence: ['State why raw scores are not probabilities.', 'Predict how score gaps affect shares.'],
    commonMisconceptions: ['Softmax simply divides each score by the sum of scores.'],
  }),
  node({
    id: 'prob.cross-entropy',
    title: 'Cross-Entropy For Next Tokens',
    track: 'probability',
    stage: 'problem-framing',
    summary:
      'Decoder training rewards high probability on the true next token at every position.',
    sourceAnchors: [page('0223'), page('0224')],
    prerequisites: ['prob.softmax-normalization'],
    equation: '\\mathcal{L}=-\\sum_{t}\\log p(x_{t+1}\\mid x_{\\leq t})',
    graph: { x: 20, y: 60 },
    lesson: lesson(
      'If the true next token receives probability 0.9 instead of 0.1, should the loss be smaller or larger?',
      'Smaller. Cross-entropy punishes low probability assigned to the correct token.',
      'For a decoder, each position produces a vocabulary distribution. The loss collects $-\\log$ probability of the actual next token.',
      'Compare $-\\log(0.9)$ and $-\\log(0.1)$ qualitatively, then explain which prediction is better.',
      'The trap is thinking the model is trained only on the final generated word. In teacher forcing, many positions contribute loss.',
    ),
    littlePath: ['Pick the true next token.', 'Read its probability.', 'Convert confidence into loss.'],
    masteryEvidence: ['Interpret next-token cross-entropy.', 'Explain why every position can contribute a training term.'],
    commonMisconceptions: ['Only the last token in a sentence contributes to decoder loss.'],
  }),
  node({
    id: 'code.token-indexing',
    title: 'Token Lists And Positions',
    track: 'coding',
    stage: 'text-pipeline',
    summary:
      'A tokenized sentence is an ordered list; indexing errors quickly become model-shape errors.',
    sourceAnchors: [page('0217'), page('0218')],
    prerequisites: ['problem.variable-length-text'],
    equation: 'tokens = [t_1,t_2,\\ldots,t_N]',
    graph: { x: 20, y: 78 },
    lesson: lesson(
      'In `tokens = ["we", "learn", "attention"]`, what is `tokens[1]` in Python?',
      'It is "learn", because Python uses zero-based indexing.',
      'The math may label tokens $t_1,\\ldots,t_N$, while Python uses indices `0..N-1`. A serious implementation keeps both conventions explicit.',
      'Write the Python index for the third token and the math subscript for the same token.',
      'A common bug is mixing one-based paper notation with zero-based code.',
    ),
    littlePath: ['Read one list index.', 'Map code index to math position.', 'Use the mapping in a tensor row.'],
    masteryEvidence: ['Index token lists correctly.', 'Translate between math and Python position conventions.'],
    commonMisconceptions: ['The second token has index 2 in Python.'],
  }),
  node({
    id: 'nlp.subword-tokenization',
    title: 'Subword Tokenization',
    track: 'nlp',
    stage: 'text-pipeline',
    summary:
      'Subword tokenizers build a finite vocabulary of characters, fragments, words, and punctuation-like units.',
    sourceAnchors: [page('0217'), page('0218')],
    prerequisites: ['code.token-indexing'],
    equation: 'text \\rightarrow [\\text{token}_1,\\ldots,\\text{token}_N]',
    graph: { x: 32, y: 10 },
    lesson: lesson(
      'Why not make every rare word its own never-before-seen symbol?',
      'Because the model needs a finite vocabulary and a way to represent rare or new words from reusable pieces.',
      'A subword tokenizer repeatedly merges common adjacent pieces until it reaches a vocabulary budget. The resulting sequence length and token identities shape the transformer input.',
      'Tokenize "unhappiness" as a plausible set of reusable pieces, then explain why that may help a rare word.',
      'The trap is assuming tokens are always full words. Modern language models often use word fragments.',
    ),
    littlePath: ['Start from characters.', 'Merge one common pair.', 'Notice vocabulary size and sequence length trade off.'],
    masteryEvidence: ['Explain why subwords are useful.', 'Predict how tokenization changes sequence length.'],
    commonMisconceptions: ['A transformer only works on complete dictionary words.'],
  }),
  node({
    id: 'nlp.one-hot-vocabulary',
    title: 'Vocabulary And One-Hot Columns',
    track: 'nlp',
    stage: 'text-pipeline',
    summary:
      'Before embeddings, each token can be represented as a one-hot column selecting a vocabulary entry.',
    sourceAnchors: [page('0218')],
    prerequisites: ['nlp.subword-tokenization'],
    equation: '\\mathbf{T}\\in\\mathbb{R}^{|V|\\times N}',
    graph: { x: 32, y: 24 },
    lesson: lesson(
      'If the vocabulary has 30,000 tokens, how many ones appear in one token column of $T$?',
      'Exactly one. The column says which vocabulary item this position contains.',
      'The matrix $T$ has one column per sequence position and one row per vocabulary item. It is sparse but conceptually simple.',
      'For a vocabulary ["a","cat","sat"], write the one-hot vector for "cat".',
      'Do not confuse one-hot vectors with learned embeddings. One-hot selects; embeddings represent.',
    ),
    littlePath: ['Make a tiny vocabulary.', 'Select one token with a one-hot vector.', 'Stack token columns into $T$.'],
    masteryEvidence: ['Construct one-hot vectors.', 'State the shape of the token indicator matrix.'],
    commonMisconceptions: ['A one-hot vector already contains semantic similarity.'],
  }),
  node({
    id: 'nlp.embedding-lookup',
    title: 'Embedding Lookup Matrix',
    track: 'nlp',
    stage: 'text-pipeline',
    summary:
      'The embedding matrix maps one-hot token columns to dense learned token vectors.',
    sourceAnchors: [page('0218')],
    prerequisites: ['nlp.one-hot-vocabulary', 'math.matrix-linear-map'],
    equation: '\\mathbf{X}=\\Omega_e\\mathbf{T},\\quad \\Omega_e\\in\\mathbb{R}^{D\\times |V|}',
    graph: { x: 32, y: 38 },
    lesson: lesson(
      'What does multiplying an embedding matrix by a one-hot vector select?',
      'It selects one column of the embedding matrix: the learned vector for that token.',
      'The whole sequence embedding is $X=\\Omega_eT$. For vocabulary size $|V|$ and embedding width $D$, $\\Omega_e$ stores $D|V|$ learned parameters.',
      'If $D=4$ and $|V|=6$, write the shape of $\\Omega_e$ and the output shape for 3 tokens.',
      'The trap is treating embeddings as hand-written definitions. They are learned parameters used by the rest of the network.',
    ),
    littlePath: ['Select one column.', 'Select three columns.', 'Call the selected columns token embeddings.'],
    masteryEvidence: ['Compute embedding matrix shape.', 'Explain lookup as matrix multiplication.'],
    commonMisconceptions: ['The embedding for a word is computed from its spelling alone.'],
  }),
  node({
    id: 'nlp.positional-encoding',
    title: 'Positional Encoding',
    track: 'nlp',
    stage: 'text-pipeline',
    summary:
      'Self-attention alone is permutation equivariant, so position information must be added or encoded separately.',
    sourceAnchors: [page('0213'), page('0214')],
    prerequisites: ['nlp.embedding-lookup'],
    equation: '\\mathbf{X}_{pos}=\\mathbf{X}+\\Pi',
    graph: { x: 32, y: 52 },
    lesson: lesson(
      'If attention sees the same token vectors in a shuffled order, what tells it which word came first?',
      'Nothing unless we provide position information. Positional encoding gives the model order clues.',
      'Absolute encodings add a unique vector per position. Relative encodings modify attention based on offsets between positions.',
      'Swap two token columns and explain why plain self-attention cannot know which ordering was original.',
      'The trap is saying transformers ignore order forever. They ignore order only if no position signal is supplied.',
    ),
    littlePath: ['Shuffle a two-token sequence.', 'Observe the ambiguity.', 'Add a position vector as the missing clue.'],
    masteryEvidence: ['Explain permutation equivariance.', 'Distinguish absolute and relative position signals.'],
    commonMisconceptions: ['The token index is automatically visible to matrix multiplication.'],
  }),
  node({
    id: 'attention.values',
    title: 'Values: Content To Mix',
    track: 'attention',
    stage: 'attention-mechanics',
    summary:
      'Values are the token-specific content vectors that attention will route and mix.',
    sourceAnchors: [page('0208'), page('0209'), page('0210')],
    prerequisites: ['math.matrix-linear-map', 'math.weighted-average'],
    equation: '\\mathbf{v}_m=\\boldsymbol{\\beta}_v+\\Omega_v\\mathbf{x}_m',
    graph: { x: 44, y: 8 },
    lesson: lesson(
      'In an attention mixture, what object is actually being mixed?',
      'The value vectors. Scores choose shares; values supply the content.',
      'Each input token produces a value vector with the same shared map. Later, attention weights combine these values for each output token.',
      'Given two values and weights 0.7 and 0.3, compute the output vector coordinate by coordinate.',
      'Do not say queries are mixed into the output. Queries ask; values answer with content.',
    ),
    littlePath: ['Compute one value vector.', 'Assign mixture weights.', 'Produce one output vector.'],
    masteryEvidence: ['Identify values as mixed content.', 'Compute a tiny value mixture.'],
    commonMisconceptions: ['Queries and keys are the vectors being averaged into the output.'],
  }),
  node({
    id: 'attention.queries-keys',
    title: 'Queries And Keys',
    track: 'attention',
    stage: 'attention-mechanics',
    summary:
      'A query asks what this position needs; keys describe what each source position offers for matching.',
    sourceAnchors: [page('0210'), page('0211')],
    prerequisites: ['math.dot-product', 'attention.values'],
    equation: '\\mathbf{q}_n=\\boldsymbol{\\beta}_q+\\Omega_q\\mathbf{x}_n,\\quad \\mathbf{k}_m=\\boldsymbol{\\beta}_k+\\Omega_k\\mathbf{x}_m',
    graph: { x: 44, y: 20 },
    lesson: lesson(
      'Which vector belongs to the token asking the question: query or key?',
      'The query. The keys belong to candidate source tokens being matched against that query.',
      'Attention forms a score for each pair $(m,n)$ by comparing key $m$ with query $n$. Queries and keys must have compatible dimensions.',
      'For one query and three keys, list the three scores that must be computed.',
      'The trap is reversing row meaning: a key does not ask all queries for help; the query token asks all keys.',
    ),
    littlePath: ['Name the asking token.', 'Name the candidate source tokens.', 'Compute pairwise matches.'],
    masteryEvidence: ['Distinguish query from key roles.', 'Set up one query against multiple keys.'],
    commonMisconceptions: ['Keys are the final output content.'],
  }),
  node({
    id: 'attention.score-matrix',
    title: 'Attention Score Matrix',
    track: 'attention',
    stage: 'attention-mechanics',
    summary:
      'All query-key dot products form a matrix of unnormalized attention scores.',
    sourceAnchors: [page('0210'), page('0211'), page('0212')],
    prerequisites: ['attention.queries-keys'],
    equation: '\\mathbf{S}=\\mathbf{K}^T\\mathbf{Q}',
    graph: { x: 44, y: 32 },
    lesson: lesson(
      'For 4 tokens, how many query-key scores are there before masking?',
      'Sixteen, one for each source-token and target-token pair.',
      'With $K,Q\\in\\mathbb{R}^{D_q\\times N}$, $K^TQ$ has shape $N\\times N$. Each entry compares one key column with one query column.',
      'Write the shape of $K^TQ$ for $N=5,D_q=64$. Which dimension disappears into the dot product?',
      'The trap is thinking the attention matrix has shape $D\\times D$. It relates token positions, not feature coordinates.',
    ),
    littlePath: ['Draw a 3 by 3 table.', 'Fill one cell with a dot product.', 'Name the full table a score matrix.'],
    masteryEvidence: ['Infer $N\\times N$ score shape.', 'Explain which axes scores relate.'],
    commonMisconceptions: ['Attention scores compare feature dimensions rather than token positions.'],
  }),
  node({
    id: 'attention.softmax-row',
    title: 'Normalize One Attention Row',
    track: 'attention',
    stage: 'attention-mechanics',
    summary:
      'Softmax is applied across the candidate source tokens for a given query position.',
    sourceAnchors: [page('0210'), page('0211'), page('0212')],
    prerequisites: ['attention.score-matrix', 'prob.softmax-normalization'],
    equation: 'a_{mn}=\\mathrm{softmax}_m(s_{mn})',
    graph: { x: 44, y: 44 },
    lesson: lesson(
      'When token n asks a question, should its attention shares sum over source tokens or feature dimensions?',
      'Over source tokens. One query distributes its attention budget across possible sources.',
      'The notation $\\mathrm{softmax}_m$ means normalize over source index $m$ while holding target/query index $n$ fixed.',
      'Take one row or column convention and explicitly mark which axis sums to 1.',
      'Different texts use row-major or column-major attention matrices. The invariant is: one query gets one distribution over sources.',
    ),
    littlePath: ['Pick one query token.', 'List its raw source scores.', 'Normalize those scores into one distribution.'],
    masteryEvidence: ['Identify the normalized axis.', 'Read one attention distribution in plain language.'],
    commonMisconceptions: ['Softmax is applied once over the entire $N\\times N$ score matrix.'],
  }),
  node({
    id: 'attention.weighted-sum-output',
    title: 'Compute One Attention Output',
    track: 'attention',
    stage: 'attention-mechanics',
    summary:
      'One output token representation is the weighted mixture of all value vectors using its attention distribution.',
    sourceAnchors: [page('0208'), page('0209'), page('0211')],
    prerequisites: ['attention.values', 'attention.softmax-row'],
    equation: '\\mathbf{y}_n=\\sum_{m=1}^{N}a_{mn}\\mathbf{v}_m',
    graph: { x: 44, y: 56 },
    lesson: lesson(
      'After token n has attention shares, what is the next concrete operation?',
      'Use those shares to mix the value vectors into output $y_n$.',
      'The scores are not the output. The distribution $a_{mn}$ is a routing table, and the values are the routed content.',
      'Compute one two-dimensional output from three two-dimensional values and three weights.',
      'A common trap is stopping at the attention matrix. Attention is only useful because it creates new token representations.',
    ),
    littlePath: ['Choose one query row.', 'Attach it to value vectors.', 'Add the weighted vectors.'],
    masteryEvidence: ['Compute one output vector.', 'Explain scores versus weights versus values.'],
    commonMisconceptions: ['The attention matrix itself is the final token embedding.'],
  }),
  node({
    id: 'attention.matrix-form',
    title: 'Self-Attention In Matrix Form',
    track: 'attention',
    stage: 'attention-mechanics',
    summary:
      'The full self-attention operation can be implemented efficiently with matrix multiplications and column-wise softmax.',
    sourceAnchors: [page('0212'), page('0213')],
    prerequisites: ['attention.weighted-sum-output'],
    equation: '\\mathrm{Sa}[X]=V\\cdot\\mathrm{softmax}(K^TQ)',
    graph: { x: 44, y: 68 },
    lesson: lesson(
      'Why write the whole attention mechanism as matrices after doing one row by hand?',
      'Because the matrix form performs every query row in parallel while preserving the same operation.',
      'UDL writes $Sa[X]=V\\cdot softmax(K^TQ)$. This is the compact version of computing all query-key scores and all weighted value mixtures.',
      'Annotate the shape of $V$, $K^TQ$, and the final output for $D=4,N=3$.',
      'The trap is memorizing the formula without knowing which sub-computation each term replaces.',
    ),
    littlePath: ['Compute one output by hand.', 'Compute two at once.', 'Accept the matrix formula as compression.'],
    masteryEvidence: ['Trace each term in the matrix formula.', 'Check compatible matrix shapes.'],
    commonMisconceptions: ['The matrix formula is a different algorithm from row-by-row attention.'],
  }),
  node({
    id: 'attention.scaled-dot-product',
    title: 'Scaled Dot-Product Attention',
    track: 'attention',
    stage: 'attention-mechanics',
    summary:
      'Dividing scores by the square root of key/query width prevents softmax saturation and improves training.',
    sourceAnchors: [page('0214')],
    prerequisites: ['attention.matrix-form'],
    equation: '\\mathrm{Sa}[X]=V\\cdot\\mathrm{softmax}\\left(\\frac{K^TQ}{\\sqrt{D_q}}\\right)',
    graph: { x: 44, y: 80 },
    lesson: lesson(
      'What happens if dot products become very large before softmax?',
      'The largest score dominates and gradients through the smaller scores can become tiny.',
      'Scaling by $\\sqrt{D_q}$ keeps score magnitudes in a healthier range as query/key dimension grows.',
      'Compare softmax behavior for scores [1,2,3] versus [10,20,30] without computing exact values.',
      'Scaling is not a probability trick after softmax; it changes scores before normalization.',
    ),
    littlePath: ['Make scores bigger.', 'Observe sharper softmax.', 'Introduce scaling as a stabilizer.'],
    masteryEvidence: ['Explain why scaling is used.', 'Place the scaling before softmax.'],
    commonMisconceptions: ['The scaling divides final attention weights by $\\sqrt{D_q}$.'],
  }),
  node({
    id: 'attention.permutation-equivariance',
    title: 'Permutation Equivariance',
    track: 'math',
    stage: 'attention-mechanics',
    summary:
      'Plain self-attention treats reordered token columns consistently, which is why positional information is required.',
    sourceAnchors: [page('0213'), page('0239')],
    prerequisites: ['attention.matrix-form', 'nlp.positional-encoding'],
    equation: '\\mathrm{Sa}[XP]=\\mathrm{Sa}[X]P',
    graph: { x: 44, y: 92 },
    lesson: lesson(
      'If every token column is permuted, should plain self-attention break or permute its outputs the same way?',
      'It permutes outputs the same way. That is equivariance, not chaos.',
      'For a permutation matrix $P$, UDL asks learners to show $Sa[XP]=Sa[X]P$. This means self-attention alone has no native absolute order.',
      'Explain the equation in words without proving it fully: what happens to outputs when inputs are reordered?',
      'Do not confuse equivariance with invariance. The outputs move with the inputs; they do not become identical.',
    ),
    littlePath: ['Swap two columns.', 'Track the corresponding outputs.', 'Name the behavior equivariance.'],
    masteryEvidence: ['Distinguish invariance and equivariance.', 'Explain why position encoding matters.'],
    commonMisconceptions: ['Permutation equivariant means the output does not change at all.'],
  }),
  node({
    id: 'attention.multi-head',
    title: 'Multiple Attention Heads',
    track: 'attention',
    stage: 'transformer-layer',
    summary:
      'Multiple heads run separate attention mechanisms in parallel and then recombine their outputs.',
    sourceAnchors: [page('0214'), page('0215'), page('0239')],
    prerequisites: ['attention.scaled-dot-product'],
    equation: '\\mathbf{Sa}_h[X]=V_h\\cdot\\mathrm{softmax}\\left(\\frac{K_h^TQ_h}{\\sqrt{D_q}}\\right)',
    graph: { x: 58, y: 10 },
    lesson: lesson(
      'Why might one attention pattern not be enough?',
      'A sentence can contain several relationships at once: local syntax, long-range reference, phrase boundaries, and more.',
      'Each head has its own $Q,K,V$ parameters. The heads produce parallel views, usually with lower per-head dimension.',
      'For model width $D=1024$ and $H=16$, compute the usual per-head width $D/H$.',
      'Heads are not identical repeats. They are separately parameterized routes that are later combined.',
    ),
    littlePath: ['Give one head one relationship.', 'Give another head a different relationship.', 'Concatenate their outputs.'],
    masteryEvidence: ['Compute per-head dimension.', 'Explain why heads can specialize.'],
    commonMisconceptions: ['More heads means running the exact same attention calculation many times.'],
  }),
  node({
    id: 'transformer.output-projection',
    title: 'Concatenate And Project Heads',
    track: 'architecture',
    stage: 'transformer-layer',
    summary:
      'Head outputs are concatenated and mapped back into the model width so the next block sees the expected shape.',
    sourceAnchors: [page('0214'), page('0215')],
    prerequisites: ['attention.multi-head'],
    equation: '\\mathrm{MhSa}[X]=\\Omega_c\\,[H_1;\\ldots;H_H]',
    graph: { x: 58, y: 24 },
    lesson: lesson(
      'After several heads speak, what makes their combined output fit the next layer?',
      'A learned output projection recombines concatenated head channels back into the model representation space.',
      'Concatenation preserves all head outputs; $\\Omega_c$ learns how to mix them into the model width used by residual paths.',
      'If 8 heads each produce width 64, what is the concatenated width before projection?',
      'The trap is averaging heads too early. Standard multi-head attention concatenates then projects.',
    ),
    littlePath: ['Place head outputs side by side.', 'Count the width.', 'Project back to model width.'],
    masteryEvidence: ['Infer concatenated head shape.', 'Explain the output projection role.'],
    commonMisconceptions: ['Head outputs are simply averaged into one vector.'],
  }),
  node({
    id: 'transformer.residual-path',
    title: 'Residual Path Around Attention',
    track: 'architecture',
    stage: 'transformer-layer',
    summary:
      'The attention update is added to the incoming representation, preserving an easy route for existing information.',
    sourceAnchors: [page('0215'), page('0216')],
    prerequisites: ['transformer.output-projection'],
    equation: 'X \\leftarrow X+\\mathrm{MhSa}[X]',
    graph: { x: 58, y: 38 },
    lesson: lesson(
      'Why add the old representation back after attention?',
      'So the layer can update information without forcing every feature to be rebuilt from scratch.',
      'Residual addition requires shape preservation: the attention output must match $X$ so the sum is defined.',
      'Write the shape condition needed for $X+MhSa[X]$ to be valid.',
      'The trap is viewing a layer as replacement only. In residual networks, layers often learn corrections.',
    ),
    littlePath: ['Keep the old vector.', 'Compute an update.', 'Add old plus update.'],
    masteryEvidence: ['State residual shape requirement.', 'Explain update rather than replacement.'],
    commonMisconceptions: ['Residual addition doubles the token count.'],
  }),
  node({
    id: 'transformer.layernorm',
    title: 'LayerNorm Per Embedding',
    track: 'architecture',
    stage: 'transformer-layer',
    summary:
      'LayerNorm normalizes each token embedding across its feature dimensions, stabilizing repeated layers.',
    sourceAnchors: [page('0215'), page('0216'), page('0238')],
    prerequisites: ['transformer.residual-path'],
    equation: 'X \\leftarrow \\mathrm{LayerNorm}(X)',
    graph: { x: 58, y: 52 },
    lesson: lesson(
      'Across which axis does LayerNorm normalize one token embedding?',
      'Across the feature dimensions of that embedding, not across all tokens as a group.',
      'LayerNorm computes statistics within each embedding vector. In transformer layers, it is commonly placed around attention and MLP residual branches.',
      'For one token vector of length 4, describe what values are used to compute its mean.',
      'Do not confuse LayerNorm with BatchNorm. The normalization unit and statistics are different.',
    ),
    littlePath: ['Take one token vector.', 'Compute feature statistics.', 'Apply the same idea to every token separately.'],
    masteryEvidence: ['Describe LayerNorm axis.', 'Explain why normalization helps layer stacks.'],
    commonMisconceptions: ['LayerNorm averages statistics across sequence positions.'],
  }),
  node({
    id: 'transformer.mlp',
    title: 'Token-Wise MLP',
    track: 'architecture',
    stage: 'transformer-layer',
    summary:
      'After tokens interact through attention, the same MLP is applied separately to each token representation.',
    sourceAnchors: [page('0215'), page('0216')],
    prerequisites: ['transformer.layernorm'],
    equation: '\\mathbf{x}_n \\leftarrow \\mathbf{x}_n+\\mathrm{mlp}(\\mathbf{x}_n)',
    graph: { x: 58, y: 66 },
    lesson: lesson(
      'Which part of the transformer layer mixes information between tokens: attention or the MLP?',
      'Attention mixes across tokens. The MLP transforms each token separately with shared parameters.',
      'The MLP branch expands and contracts feature channels for each token column. It is position-wise but reused across positions.',
      'Explain why the MLP can change token features but cannot directly read another token unless attention already routed information in.',
      'The trap is saying every sublayer performs token-to-token communication. The MLP is local to a token representation.',
    ),
    littlePath: ['Let attention exchange information.', 'Freeze token positions.', 'Apply the same MLP to each column.'],
    masteryEvidence: ['Distinguish attention mixing from token-wise MLP transformation.', 'Explain parameter sharing in the MLP.'],
    commonMisconceptions: ['The MLP is where each token attends to every other token.'],
  }),
  node({
    id: 'transformer.layer-stack',
    title: 'Stacked Transformer Layers',
    track: 'architecture',
    stage: 'transformer-layer',
    summary:
      'A transformer model repeatedly applies shape-preserving layers so representations become more contextual.',
    sourceAnchors: [page('0216'), page('0218')],
    prerequisites: ['transformer.mlp'],
    equation: 'X^{(k+1)}=\\mathrm{TransformerLayer}(X^{(k)})',
    graph: { x: 58, y: 82 },
    lesson: lesson(
      'Why can a transformer apply many layers without changing the external sequence shape?',
      'Each layer returns the same token count and model width, so the next layer accepts the same kind of object.',
      'Layer stacks let information routed in earlier layers become input to later routing and token-wise computation.',
      'For $K=24$ layers, state what stays fixed about $X$ from layer to layer.',
      'The trap is assuming deeper layers add more token positions. They update representations, not sequence length.',
    ),
    littlePath: ['Check one layer input/output shape.', 'Apply a second compatible layer.', 'Name the repeated model.'],
    masteryEvidence: ['Explain stackability.', 'Track what stays fixed through repeated layers.'],
    commonMisconceptions: ['Each transformer layer consumes or deletes one token.'],
  }),
  node({
    id: 'model.encoder',
    title: 'Encoder Visibility',
    track: 'architecture',
    stage: 'model-architectures',
    summary:
      'An encoder lets every token attend to every other token and produces representations for understanding tasks.',
    sourceAnchors: [page('0218'), page('0219'), page('0220')],
    prerequisites: ['transformer.layer-stack'],
    equation: '\\text{encoder: all tokens may attend to all tokens}',
    graph: { x: 72, y: 8 },
    lesson: lesson(
      'In an encoder, can a token use information from tokens to its left and right?',
      'Yes. Encoder self-attention is unmasked, so the whole input context is visible.',
      'This makes encoders natural for representation tasks: classification, tagging, span prediction, and masked-token pre-training.',
      'Draw a 5 by 5 visibility matrix for an encoder and mark which entries are allowed.',
      'Do not use encoder visibility for next-token generation during training unless the task is designed for bidirectional context.',
    ),
    littlePath: ['Mark all pairwise token interactions.', 'Attach a downstream task head.', 'Name it encoder-style use.'],
    masteryEvidence: ['Describe encoder attention visibility.', 'Match encoders to understanding tasks.'],
    commonMisconceptions: ['Encoders and decoders differ only in parameter count.'],
  }),
  node({
    id: 'model.bert-pretraining',
    title: 'BERT-Style Masked Pre-Training',
    track: 'training',
    stage: 'model-architectures',
    summary:
      'BERT-style encoders learn from unlabeled text by predicting intentionally masked tokens.',
    sourceAnchors: [page('0219'), page('0220')],
    prerequisites: ['model.encoder', 'prob.cross-entropy'],
    equation: 'p(t_i\\mid t_{\\setminus i})',
    graph: { x: 72, y: 19 },
    lesson: lesson(
      'If a word is replaced by `<mask>`, what does the encoder have to learn to predict it?',
      'It must use both left and right context to infer a plausible missing token.',
      'Masked-token pre-training creates labels from the text itself. A few positions contribute loss while the full context is processed.',
      'Given "the red <mask> stopped", list two plausible and one implausible missing tokens.',
      'The trap is saying the data is unlabeled so there is no target. The target is constructed from the hidden token.',
    ),
    littlePath: ['Hide one token.', 'Use surrounding context.', 'Score the original token.'],
    masteryEvidence: ['Explain self-supervised masked-token prediction.', 'Connect encoder visibility to BERT pre-training.'],
    commonMisconceptions: ['Masked pre-training has no labels of any kind.'],
  }),
  node({
    id: 'model.finetuning-heads',
    title: 'Fine-Tuning Heads',
    track: 'training',
    stage: 'model-architectures',
    summary:
      'After pre-training, encoder representations feed task-specific heads for classification, tagging, or span prediction.',
    sourceAnchors: [page('0221'), page('0222')],
    prerequisites: ['model.bert-pretraining'],
    equation: '\\hat{y}=\\mathrm{head}(\\mathbf{x}_{cls})',
    graph: { x: 72, y: 30 },
    lesson: lesson(
      'For sentiment classification, why might a special `<cls>` representation be useful?',
      'It gives the model one designated vector to summarize the sequence for a whole-text prediction.',
      'Fine-tuning attaches a small head to encoder outputs. The head may read the `<cls>` token, every token, or start/end logits depending on the task.',
      'Choose the right output representation for sentiment, named entity recognition, and answer-span prediction.',
      'The trap is thinking the whole encoder must be redesigned for every task. Often the base is reused and the head changes.',
    ),
    littlePath: ['Pick the task output type.', 'Select which encoder vectors matter.', 'Attach a small prediction head.'],
    masteryEvidence: ['Match tasks to fine-tuning heads.', 'Explain the role of `<cls>`.'],
    commonMisconceptions: ['Fine-tuning always predicts exactly one class from exactly one token.'],
  }),
  node({
    id: 'model.decoder-autoregressive',
    title: 'Autoregressive Decoder',
    track: 'training',
    stage: 'model-architectures',
    summary:
      'A decoder models a sequence as a product of next-token conditional probabilities.',
    sourceAnchors: [page('0222'), page('0223')],
    prerequisites: ['transformer.layer-stack', 'prob.cross-entropy'],
    equation: 'p(t_1,\\ldots,t_N)=\\prod_{n=1}^{N}p(t_n\\mid t_{<n})',
    graph: { x: 72, y: 42 },
    lesson: lesson(
      'How can a model assign probability to a whole sentence one token at a time?',
      'Factor the joint probability into next-token predictions conditioned on the prefix.',
      'Autoregressive decoding asks the model to predict the next token from previous tokens. This is the probability backbone of GPT-style models.',
      'Write the conditional factors for a three-token sequence.',
      'The trap is thinking the model predicts every token independently. Each prediction is conditioned on the prefix.',
    ),
    littlePath: ['Predict token 1.', 'Condition token 2 on token 1.', 'Generalize to the product rule.'],
    masteryEvidence: ['Factor a short sequence probability.', 'Explain next-token modeling.'],
    commonMisconceptions: ['Autoregressive means the model ignores previous tokens.'],
  }),
  node({
    id: 'model.masked-self-attention',
    title: 'Causal Masked Self-Attention',
    track: 'attention',
    stage: 'model-architectures',
    summary:
      'Decoder self-attention blocks future tokens by setting forbidden scores to negative infinity before softmax.',
    sourceAnchors: [page('0223'), page('0224')],
    prerequisites: ['model.decoder-autoregressive', 'attention.softmax-row'],
    equation: 's_{mn}=-\\infty\\quad \\text{when }m>n',
    graph: { x: 72, y: 54 },
    lesson: lesson(
      'Why is it cheating if position n can attend to token n+1 while learning to predict token n+1?',
      'Because the answer leaks into the representation. The model would learn to copy future information instead of predict it.',
      'The causal mask edits the score matrix before softmax. Forbidden future positions receive zero attention after normalization.',
      'Draw the allowed lower-triangular attention pattern for four tokens.',
      'The mask must be applied before softmax. Masking weights after softmax can leave normalization broken.',
    ),
    littlePath: ['Play a next-token game.', 'Notice the future-token leak.', 'Block future scores before normalization.'],
    masteryEvidence: ['Apply a causal mask.', 'Explain why masking prevents training leakage.'],
    commonMisconceptions: ['A decoder can see future tokens during training because the whole sentence is available.'],
  }),
  node({
    id: 'model.decoder-training',
    title: 'Teacher Forcing And Parallel Loss',
    track: 'training',
    stage: 'model-architectures',
    summary:
      'During training, the full ground-truth sequence is fed in, but causal masks let all next-token losses be computed safely.',
    sourceAnchors: [page('0223'), page('0224')],
    prerequisites: ['model.masked-self-attention'],
    equation: '\\mathcal{L}= -\\sum_{n=1}^{N-1}\\log p(t_{n+1}\\mid t_{\\le n})',
    graph: { x: 72, y: 66 },
    lesson: lesson(
      'How can the model train on all positions in one forward pass without seeing answers?',
      'It uses the ground-truth sequence as input but masks future attention, so each position only has prefix information.',
      'Teacher forcing means the input prefix uses real previous tokens during training. The loss asks each position to predict the following token.',
      'For a 5-token sentence with a start token, count how many next-token training targets can be produced.',
      'Do not confuse training input with generation input. During generation, the model feeds back its own sampled tokens.',
    ),
    littlePath: ['Feed the real prefix.', 'Mask future positions.', 'Collect one loss per next-token prediction.'],
    masteryEvidence: ['Explain teacher forcing.', 'Count parallel training targets.'],
    commonMisconceptions: ['Teacher forcing removes the need for a causal mask.'],
  }),
  node({
    id: 'model.generation-cache',
    title: 'Generation And KV Cache',
    track: 'systems',
    stage: 'model-architectures',
    summary:
      'At generation time, previous key/value computations can be reused while new tokens extend the sequence one step at a time.',
    sourceAnchors: [page('0224'), page('0235'), page('0239')],
    prerequisites: ['model.decoder-training'],
    equation: 'p(t_{n+1}\\mid t_{\\le n})\\rightarrow t_{n+1}',
    graph: { x: 72, y: 78 },
    lesson: lesson(
      'When generating token 101, should the model recompute every old key and value from scratch if nothing old changed?',
      'It can reuse cached keys and values for previous tokens, then compute the new token contribution.',
      'Because causal masking prevents later tokens from changing earlier representations in a decoder pass, cached key/value tensors make generation more efficient.',
      'Describe what new computation is needed after appending one new token to a cached prefix.',
      'The trap is thinking training and inference have identical compute patterns. They share parameters but use different schedules.',
    ),
    littlePath: ['Generate one token.', 'Append it to the prefix.', 'Reuse what the prefix already computed.'],
    masteryEvidence: ['Explain autoregressive generation loop.', 'Describe what a KV cache stores.'],
    commonMisconceptions: ['KV caching changes the mathematical output of the model.'],
  }),
  node({
    id: 'model.encoder-decoder',
    title: 'Encoder-Decoder Translation',
    track: 'architecture',
    stage: 'model-architectures',
    summary:
      'Sequence-to-sequence models encode a source sentence and decode a target sentence with both masked self-attention and cross-attention.',
    sourceAnchors: [page('0226'), page('0227')],
    prerequisites: ['model.encoder', 'model.masked-self-attention'],
    equation: 'X_{src}\\rightarrow H_{enc},\\quad p(y_t\\mid y_{<t},H_{enc})',
    graph: { x: 72, y: 90 },
    lesson: lesson(
      'In translation, where should the target-language decoder look for source-language meaning?',
      'At the encoder outputs. That is the job of encoder-decoder attention.',
      'The encoder reads the source sentence bidirectionally. The decoder predicts target tokens causally while also attending to encoder representations.',
      'Separate the three flows: source self-attention, target masked self-attention, and target-to-source cross-attention.',
      'The trap is saying the decoder only attends to its own generated prefix in translation. It also attends to the source encoding.',
    ),
    littlePath: ['Encode source text.', 'Mask target prefix.', 'Add a bridge from target queries to source memories.'],
    masteryEvidence: ['Describe encoder-decoder data flow.', 'Distinguish self-attention from cross-attention.'],
    commonMisconceptions: ['Translation decoders never inspect the source sentence after encoding begins.'],
  }),
  node({
    id: 'model.cross-attention',
    title: 'Cross-Attention',
    track: 'attention',
    stage: 'model-architectures',
    summary:
      'Cross-attention uses decoder queries with encoder keys and values, letting target positions retrieve source information.',
    sourceAnchors: [page('0227')],
    prerequisites: ['model.encoder-decoder', 'attention.queries-keys'],
    equation: '\\mathrm{CrossAttn}=V_{enc}\\cdot\\mathrm{softmax}\\left(K_{enc}^TQ_{dec}\\right)',
    graph: { x: 84, y: 16 },
    lesson: lesson(
      'In cross-attention, do keys and values come from the same stream as the queries?',
      'No. Queries come from the decoder, while keys and values come from encoder outputs.',
      'This lets each target-side position ask which source-side representations matter for the next translated token.',
      'Label $Q$, $K$, and $V$ sources in a translation block diagram.',
      'The trap is applying a causal mask to encoder keys as if they were target future tokens. Source tokens are already fully observed.',
    ),
    littlePath: ['Let the decoder ask.', 'Let the encoder provide addresses and content.', 'Mix source values for the target position.'],
    masteryEvidence: ['Identify Q/K/V sources in cross-attention.', 'Explain why cross-attention supports translation.'],
    commonMisconceptions: ['Cross-attention is just masked self-attention with a different name.'],
  }),
  node({
    id: 'systems.quadratic-complexity',
    title: 'Quadratic Attention Cost',
    track: 'systems',
    stage: 'scale-and-variants',
    summary:
      'Full self-attention creates pairwise token interactions, so attention matrix size grows as sequence length squared.',
    sourceAnchors: [page('0209'), page('0227'), page('0228'), page('0239')],
    prerequisites: ['attention.score-matrix'],
    equation: 'N\\text{ tokens}\\rightarrow N^2\\text{ attention scores}',
    graph: { x: 84, y: 32 },
    lesson: lesson(
      'If sequence length doubles, what happens to the number of pairwise attention scores?',
      'It grows by about four times, because every token can interact with every token.',
      'The attention matrix relates token positions. Full encoder attention has $N^2$ entries; causal decoder attention has roughly half but remains quadratic.',
      'Compare attention entries for $N=128$ and $N=256$.',
      'The trap is counting only parameters. Attention cost also depends strongly on input length at runtime.',
    ),
    littlePath: ['Count pairs for 4 tokens.', 'Count pairs for 8 tokens.', 'Name the square growth.'],
    masteryEvidence: ['Compute $N^2$ score counts.', 'Explain why long contexts are expensive.'],
    commonMisconceptions: ['Transformer runtime depends only on parameter count.'],
  }),
  node({
    id: 'systems.sparse-attention',
    title: 'Sparse And Local Attention',
    track: 'systems',
    stage: 'scale-and-variants',
    summary:
      'Long-sequence transformers reduce cost by pruning the interaction matrix with local, dilated, or global-token patterns.',
    sourceAnchors: [page('0228')],
    prerequisites: ['systems.quadratic-complexity'],
    equation: 'a_{mn}=0\\quad \\text{for many disallowed pairs}',
    graph: { x: 84, y: 48 },
    lesson: lesson(
      'How can a transformer avoid paying for every token pair while still moving information far away over layers?',
      'Restrict some layers to local or sparse interactions and let receptive fields expand through depth or global tokens.',
      'Sparse attention changes the allowed interaction pattern. Local windows, dilation, and global tokens are different compromises between cost and connectivity.',
      'Design an allowed-attention pattern for 12 tokens where each token sees only nearby tokens plus one global token.',
      'The trap is assuming sparsity always preserves full attention behavior. It changes what information can move in one layer.',
    ),
    littlePath: ['Start with all pairs.', 'Remove most far pairs.', 'Add a mechanism for long-distance communication.'],
    masteryEvidence: ['Compare dense and sparse interaction matrices.', 'Explain local versus global sparse patterns.'],
    commonMisconceptions: ['Sparse attention is free and has no modeling tradeoff.'],
  }),
  node({
    id: 'vision.image-tokens',
    title: 'Images As Token Sequences',
    track: 'vision',
    stage: 'scale-and-variants',
    summary:
      'Image transformers must turn 2D pixels or patches into a sequence and provide position information.',
    sourceAnchors: [page('0229'), page('0230')],
    prerequisites: ['nlp.positional-encoding', 'systems.quadratic-complexity'],
    equation: 'H\\times W\\text{ image}\\rightarrow N\\text{ visual tokens}',
    graph: { x: 84, y: 64 },
    lesson: lesson(
      'Why is pixel-level image attention expensive?',
      'Images have many more positions than a short sentence, so pairwise interactions explode quickly.',
      'ImageGPT treats pixels as autoregressive tokens. ViT reduces sequence length by using patches as tokens instead of individual pixels.',
      'Compare the token count of a 224 by 224 image as pixels versus 16 by 16 patches.',
      'The trap is forgetting that converting images to a sequence discards the built-in 2D inductive bias unless position and data compensate.',
    ),
    littlePath: ['Count pixel tokens.', 'Group pixels into patches.', 'Notice the sequence becomes shorter.'],
    masteryEvidence: ['Explain why image tokenization matters.', 'Relate patch size to attention cost.'],
    commonMisconceptions: ['Vision transformers can ignore spatial position because images are visual.'],
  }),
  node({
    id: 'vision.vit',
    title: 'Vision Transformer',
    track: 'vision',
    stage: 'scale-and-variants',
    summary:
      'ViT maps image patches to embeddings, adds position information, and uses an encoder with a classification token or pooled representation.',
    sourceAnchors: [page('0229'), page('0230'), page('0232')],
    prerequisites: ['vision.image-tokens', 'model.encoder'],
    equation: '\\text{patch}\\rightarrow \\text{embedding}\\rightarrow \\text{encoder}\\rightarrow \\text{class}',
    graph: { x: 84, y: 80 },
    lesson: lesson(
      'What is the image analogue of a word embedding in ViT?',
      'A learned linear projection of an image patch into the model embedding space.',
      'ViT converts fixed-size patches into embeddings, adds position encodings, runs an encoder, and maps a summary representation to class probabilities.',
      'For 16 by 16 patches in a 224 by 224 image, compute how many patch tokens are produced.',
      'The trap is thinking ViT uses convolutional filters first by definition. The core idea is patch embeddings plus transformer encoder layers.',
    ),
    littlePath: ['Cut image into patches.', 'Embed each patch.', 'Use encoder representations for classification.'],
    masteryEvidence: ['Compute patch token counts.', 'Explain how ViT adapts text-transformer machinery.'],
    commonMisconceptions: ['A patch token is the same thing as one pixel.'],
  }),
  node({
    id: 'project.tiny-masked-decoder',
    title: 'Build A Tiny Masked Decoder',
    track: 'project',
    stage: 'capstone',
    summary:
      'Implement a small decoder attention pass, inspect its attention matrix, add a causal mask, and explain one next-token distribution.',
    sourceAnchors: [page('0222'), page('0223'), page('0224'), page('0239')],
    prerequisites: ['model.masked-self-attention', 'model.decoder-training', 'attention.scaled-dot-product'],
    equation: '\\text{tokens}\\rightarrow X\\rightarrow Q,K,V\\rightarrow \\mathrm{masked\\ attention}\\rightarrow p(t_{next})',
    graph: { x: 94, y: 46 },
    lesson: lesson(
      'What should you be able to build after this course slice?',
      'A tiny inspectable decoder step: token vectors, projections, scores, mask, softmax, value mixture, and next-token probabilities.',
      'The capstone is deliberately small. It proves the learner can connect shapes, code, equations, and explanation without hiding behind a library call.',
      'Implement a four-token, two-feature masked attention calculation and print the attention matrix before and after masking.',
      'The trap is using a framework layer first. The capstone starts from explicit arrays so every operation can be inspected.',
    ),
    littlePath: ['Write tokens.', 'Compute Q/K/V.', 'Apply the mask before softmax.', 'Explain the chosen next token.'],
    masteryEvidence: ['Run the full tiny attention calculation.', 'Explain each tensor in the decoder route.', 'Debug a missing mask.'],
    commonMisconceptions: ['Calling a pretrained transformer API is the same as understanding the decoder computation.'],
  }),
]

export const course: Course = {
  id: 'udl-ch12-transformers',
  title: 'Transformer Mastery Course',
  subtitle:
    'A graph-first, source-grounded route through UDL Chapter 12 for an experienced learner who wants equations, code, and explanation to lock together.',
  target: 'Build and explain a tiny masked decoder from first principles, including Q/K/V projections, causal masking, and next-token loss.',
  nodes,
  diagnosticQuestions: [
    {
      id: 'shape',
      prompt: 'A sequence has N=37 tokens and embedding width D=1024. What scalar count describes the encoded input?',
      correctAnswer: '37888',
      repairNodeId: 'problem.variable-length-text',
      options: [
        { value: '1061', label: '37 + 1024 = 1061' },
        { value: '37888', label: '37 x 1024 = 37888' },
      ],
    },
    {
      id: 'dotProduct',
      prompt: 'For q=[1,2,3] and k=[3,1,2], what is q dot k?',
      correctAnswer: '11',
      repairNodeId: 'math.dot-product',
      options: [
        { value: '11', label: '11' },
        { value: '14', label: '14' },
      ],
    },
    {
      id: 'softmax',
      prompt: 'What does softmax do to attention scores?',
      correctAnswer: 'positive-shares',
      repairNodeId: 'prob.softmax-normalization',
      options: [
        { value: 'positive-shares', label: 'It turns scores into positive shares that sum to one.' },
        { value: 'raw-division', label: 'It divides raw scores by their raw sum.' },
      ],
    },
    {
      id: 'tokenIndexing',
      prompt: 'For tokens=["we","learn","attention"], what does tokens[1] return in Python?',
      correctAnswer: 'learn',
      repairNodeId: 'code.token-indexing',
      options: [
        { value: 'we', label: '"we"' },
        { value: 'learn', label: '"learn"' },
      ],
    },
    {
      id: 'embeddingLookup',
      prompt: 'What does multiplying an embedding matrix by a one-hot token vector select?',
      correctAnswer: 'embedding-column',
      repairNodeId: 'nlp.embedding-lookup',
      options: [
        { value: 'embedding-column', label: 'The learned embedding column for that token.' },
        { value: 'all-embeddings-average', label: 'The average of all token embeddings.' },
      ],
    },
    {
      id: 'position',
      prompt: 'Why do transformers need positional information?',
      correctAnswer: 'order-not-visible',
      repairNodeId: 'nlp.positional-encoding',
      options: [
        { value: 'order-not-visible', label: 'Plain self-attention does not know absolute order by itself.' },
        { value: 'reduce-vocab', label: 'Position encodings reduce the vocabulary size.' },
      ],
    },
    {
      id: 'scaledAttention',
      prompt: 'Where does the scaled dot-product factor appear?',
      correctAnswer: 'before-softmax',
      repairNodeId: 'attention.scaled-dot-product',
      options: [
        { value: 'before-softmax', label: 'Divide scores by sqrt(D_q) before softmax.' },
        { value: 'after-softmax', label: 'Divide final attention weights by sqrt(D_q).' },
      ],
    },
    {
      id: 'masking',
      prompt: 'In a decoder, what should happen to future-token scores before softmax?',
      correctAnswer: 'negative-infinity',
      repairNodeId: 'model.masked-self-attention',
      options: [
        { value: 'negative-infinity', label: 'Set them to negative infinity so they get zero share.' },
        { value: 'double-them', label: 'Double them so the model learns faster.' },
      ],
    },
    {
      id: 'crossAttention',
      prompt: 'In encoder-decoder cross-attention, where do keys and values come from?',
      correctAnswer: 'encoder',
      repairNodeId: 'model.cross-attention',
      options: [
        { value: 'encoder', label: 'From the encoder outputs.' },
        { value: 'decoder-future', label: 'From future decoder tokens.' },
      ],
    },
  ],
  practiceItems: nodes.map((courseNode): PracticeItem => ({
    id: practiceId(courseNode.id),
    nodeId: courseNode.id,
    kind:
      courseNode.track === 'coding' || courseNode.track === 'project'
        ? 'debug'
        : courseNode.track === 'math' || courseNode.track === 'probability'
          ? 'compute'
          : 'explain',
    prompt: `Which statement best shows mastery of ${courseNode.title}?`,
    choices: [
      {
        id: 'mastery',
        text: courseNode.masteryEvidence[0],
        correct: true,
        feedback: `Yes. That is the first mastery signal for ${courseNode.title}; now connect it to the selected equation and source anchor.`,
      },
      {
        id: 'misconception',
        text: courseNode.commonMisconceptions[0],
        correct: false,
        feedback: `Not quite. This is the misconception to repair: ${courseNode.commonMisconceptions[0]}`,
      },
    ],
  })),
}
